spring:
  profiles:
    active: local

# Local 환경
---
spring:
  profiles: local
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    ROOT: debug
